// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/welcome": {
    params: {};
  };
  "/api/vlm": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/login" | "/register" | "/welcome" | "/api/vlm";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/welcome.tsx": {
    id: "routes/welcome";
    page: "/welcome";
  };
  "routes/api.vlm.ts": {
    id: "routes/api.vlm";
    page: "/api/vlm";
  };
};